# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


# [](bg:#030B16 fg:#7DF9AA)\
format = """\
[ $os ](bg:#7DF9AA fg:#090c0c)\
[](fg:#7DF9AA bg:#1D2230)\
[${username}](bg:#1D2230 fg:#FCF392)\
[${env_var.dockerPlatform}](bg:#1D2230 fg:#FCF392)\
[${custom.onehmi}](bg:#1D2230 fg:#FCF392)\
[${custom.venv}](bg:#1D2230 fg:#FCF392)\
[${custom.spamode}](bg:#1D2230 fg:#FCF392)\
[](fg:#1D2230 bg:#1C3A5E)\
[$hostname](fg:#E4E4E4 bg:#1C3A5E)\
[](fg:#1C3A5E bg:#3B76F0)\
$directory\
[](fg:#3B76F0 bg:#FCF392)\
$git_branch\
$git_status\
[](fg:#FCF392 bg:#030B16)\
$fill\
$time\
\n$character\
"""

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[ ✗](#E84D44) '

[fill]
symbol = ' '
style = 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
style_user = 'white'
style_root = 'bold white'
format=' $user'
show_always = true

[directory]
format = "[  $path ]($style)"
style = "fg:#E4E4E4 bg:#3B76F0"
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#1C3A5E bg:#FCF392"

# [git_metrics]
# format = "([+$added]($added_style))[]($added_style)"
# added_style = "fg:#1C3A5E bg:#FCF392"
# deleted_style = "fg:bright-red bg:235"
# disabled = false

[git_status]
style = "fg:#1C3A5E bg:#FCF392"
format = '[[($all_status$ahead_behind )](fg:#1C3A5E bg:#FCF392)]($style)'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
staged = '+${count}'
untracked = '?${count}'

[hostname]
#ssh_only = false
format='$hostname'

[os]
format='$symbol'
disabled = false

[os.symbols]
Ubuntu = ""
Macos= ""
Windows = ""
Raspbian = ""
Linux = ""

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[env_var.dockerPlatform]
default = ''
format = " $env_value "

[custom.onehmi]
when = ''' test "$VCC_ONEHMI_ENABLED" == "true" '''
format = " ONEHMI "

[custom.venv]
#command = 'echo foo' # shows output of command
when = ''' test "$VIRTUAL_ENV" != "" '''
format = ' VENV '

[custom.spamode]
#command = 'echo foo' # shows output of command
when = ''' test "$OUT_DIR" == "out_emu" '''
format = ' EMU '
